## stage one - build
FROM node:14.17.3 as build

WORKDIR /home/node/app

COPY package.json ./
COPY tsconfig.json ./

COPY src ./src

RUN ls -a
RUN npm install
RUN npm run build

## stage two - production
FROM node:14.17.3 as production

WORKDIR /home/node/app

COPY package.json ./

RUN npm install --only=production

RUN echo test >> .dockerignore

COPY --from=0 /home/node/app/dist ./dist

CMD ["npm", "run", "start"]
